import { createFileRoute, Link } from "@tanstack/react-router";
import {
  ArrowRight,
  BarChart3,
  Bell,
  CandlestickChart,
  LineChart,
  Radio,
  ShieldCheck,
  Target,
  TrendingUp,
  Zap,
  LogOut,
  Loader2,
} from "lucide-react";

import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

import heroImage from "../assets/hero-forex.jpg";


export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({
    meta: [
      {
        title: "BinaryPulse — Forex & Binary Options Analysis",
      },
      {
        name: "description",
        content:
          "BinaryPulse delivers real-time forex analysis, binary options signals, volatility heatmaps and smart trade alerts for confident trading decisions.",
      },
      {
        property: "og:title",
        content: "BinaryPulse — Forex & Binary Options Analysis",
      },
      {
        property: "og:description",
        content:
          "Real-time forex analysis, binary options signals and volatility heatmaps for smarter trades.",
      },
      { property: "og:type", content: "website" },
      { property: "og:image", content: "https://id-preview--2544fda6-f75d-4f43-a91d-41f092b25258.lovable.app/images/hero-forex.jpg" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:image", content: "https://id-preview--2544fda6-f75d-4f43-a91d-41f092b25258.lovable.app/images/hero-forex.jpg" },
    ],
  }),
});

const pairs = [
  { label: "EUR/USD", value: "1.0847", change: "+0.12%", up: true },
  { label: "GBP/USD", value: "1.2679", change: "-0.05%", up: false },
  { label: "USD/JPY", value: "151.34", change: "+0.28%", up: true },
  { label: "USD/CHF", value: "0.9051", change: "-0.09%", up: false },
  { label: "AUD/USD", value: "0.6534", change: "+0.41%", up: true },
  { label: "EUR/USD", value: "1.0847", change: "+0.12%", up: true },
  { label: "GBP/USD", value: "1.2679", change: "-0.05%", up: false },
  { label: "USD/JPY", value: "151.34", change: "+0.28%", up: true },
  { label: "USD/CHF", value: "0.9051", change: "-0.09%", up: false },
  { label: "AUD/USD", value: "0.6534", change: "+0.41%", up: true },
];

const features = [
  {
    icon: Target,
    title: "Binary Signals",
    description: "High-probability CALL/PUT signals generated by multi-timeframe analysis.",
  },
  {
    icon: LineChart,
    title: "Live Charts",
    description: "Real-time candlestick charts with trend overlays and key support levels.",
  },
  {
    icon: Zap,
    title: "Volatility Heatmap",
    description: "Visualize market heat across sessions and spot explosive move zones.",
  },
  {
    icon: Bell,
    title: "Instant Alerts",
    description: "Push, email and in-app alerts so you never miss a trade setup.",
  },
  {
    icon: ShieldCheck,
    title: "Risk Management",
    description: "Position sizing, win-rate tracking and drawdown limits built in.",
  },
  {
    icon: Radio,
    title: "Session Scanner",
    description: "Track London, New York and Tokyo opens with automatic pair focus.",
  },
];

const stats = [
  { value: "89%", label: "Signal accuracy (last 30 days)" },
  { value: "12+", label: "Currency pairs covered" },
  { value: "<2s", label: "Average alert latency" },
  { value: "24/7", label: "Market monitoring" },
];

function Index() {
  return (
    <div className="relative min-h-screen overflow-x-hidden bg-background text-foreground">
      {/* Background aurora */}
      <div className="pointer-events-none fixed inset-0 -z-10 bg-aurora" />
      <div className="pointer-events-none fixed inset-0 -z-10 grid-lines opacity-30" />

      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border/40 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-gradient text-white shadow-lg shadow-primary/25">
              <CandlestickChart className="h-5 w-5" />
            </div>
            <span className="font-display text-xl font-bold tracking-tight text-foreground">
              Binary<span className="text-primary">Pulse</span>
            </span>
          </Link>

          <nav className="hidden items-center gap-8 md:flex">
            <a href="#features" className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
              Features
            </a>
            <a href="#signals" className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
              Signals
            </a>
            <a href="#pricing" className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
              Pricing
            </a>
            <a href="#faq" className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
              FAQ
            </a>
          </nav>

          <AuthHeaderButtons />

        </div>
      </header>

      <main>
        {/* Hero */}
        <section className="relative overflow-hidden px-4 pt-20 pb-24 sm:pt-28 lg:pt-36 lg:pb-32">
          <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2 lg:px-8">
            <div className="animate-rise-in max-w-2xl">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border/60 bg-surface/60 px-4 py-1.5 text-xs font-semibold text-primary backdrop-blur-sm">
                <span className="relative flex h-2 w-2">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-call opacity-75" />
                  <span className="relative inline-flex h-2 w-2 rounded-full bg-call" />
                </span>
                Live market signals updated every 60 seconds
              </div>

              <h1 className="font-display text-4xl font-extrabold leading-[1.1] text-foreground sm:text-5xl lg:text-6xl">
                Trade forex with <span className="text-gradient">precision</span> and speed.
              </h1>

              <p className="mt-6 max-w-lg text-lg leading-relaxed text-muted-foreground">
                BinaryPulse combines advanced technical analysis, volatility heatmaps and real-time alerts
                so you can take confident binary option trades in any session.
              </p>

              <div className="mt-8 flex flex-wrap items-center gap-4">
                <a
                  href="/auth"
                  className="inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3.5 text-base font-semibold text-primary-foreground shadow-xl shadow-primary/25 transition-all hover:scale-[1.02] hover:bg-primary/90 hover:shadow-primary/35"
                >
                  Get started free
                  <ArrowRight className="h-5 w-5" />
                </a>
                <a
                  href="#demo"
                  className="inline-flex items-center gap-2 rounded-xl border border-border/60 bg-surface/60 px-6 py-3.5 text-base font-semibold text-foreground backdrop-blur-sm transition-all hover:border-primary/40 hover:bg-surface-elevated"
                >
                  <BarChart3 className="h-5 w-5 text-primary" />
                  View live dashboard
                </a>
              </div>

              <div className="mt-10 flex items-center gap-4 text-sm text-muted-foreground">
                <div className="flex -space-x-2">
                  {[1, 2, 3, 4].map((i) => (
                    <div
                      key={i}
                      className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-background bg-surface-elevated text-xs font-semibold text-foreground"
                    >
                      {String.fromCharCode(64 + i)}
                    </div>
                  ))}
                </div>
                <p>
                  Trusted by <span className="font-semibold text-foreground">3,200+</span> traders worldwide
                </p>
              </div>
            </div>

            <div className="animate-rise-in relative lg:pl-8" style={{ animationDelay: "120ms" }}>
              <div className="relative rounded-2xl glass-panel p-2 glow-ring">
                <img
                  src={heroImage}
                  alt="BinaryPulse trading dashboard with candlestick charts and binary signals"
                  width={1920}
                  height={1024}
                  className="rounded-xl object-cover"
                />
                <div className="absolute -bottom-5 -left-5 rounded-xl glass-panel p-4 shadow-xl">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-full bg-call/20 text-call">
                      <TrendingUp className="h-5 w-5" />
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">Latest signal</p>
                      <p className="font-display text-lg font-bold text-foreground">EUR/USD CALL</p>
                    </div>
                  </div>
                </div>
                <div className="absolute -top-4 -right-4 rounded-xl glass-panel px-4 py-2 shadow-xl">
                  <p className="text-xs text-muted-foreground">Win rate</p>
                  <p className="font-display text-xl font-bold text-call">89.2%</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Live ticker */}
        <section className="border-y border-border/30 bg-surface/40 py-4 backdrop-blur-sm">
          <div className="relative flex overflow-hidden">
            <div className="animate-ticker flex shrink-0 items-center gap-10 whitespace-nowrap pr-10">
              {pairs.map((p, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="font-mono text-sm font-semibold text-foreground">{p.label}</span>
                  <span className="font-mono text-sm text-muted-foreground">{p.value}</span>
                  <span className={`font-mono text-xs font-bold ${p.up ? "text-call" : "text-put"}`}>
                    {p.change}
                  </span>
                </div>
              ))}
            </div>
            <div className="animate-ticker flex shrink-0 items-center gap-10 whitespace-nowrap pr-10">
              {pairs.map((p, i) => (
                <div key={`dup-${i}`} className="flex items-center gap-3">
                  <span className="font-mono text-sm font-semibold text-foreground">{p.label}</span>
                  <span className="font-mono text-sm text-muted-foreground">{p.value}</span>
                  <span className={`font-mono text-xs font-bold ${p.up ? "text-call" : "text-put"}`}>
                    {p.change}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Stats */}
        <section className="px-4 py-20 lg:py-28">
          <div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">
            {stats.map((s, i) => (
              <div
                key={i}
                className="rounded-2xl glass-panel p-6 text-center transition-all hover:-translate-y-1 hover:border-primary/40"
              >
                <p className="font-display text-4xl font-extrabold text-foreground">{s.value}</p>
                <p className="mt-1 text-sm text-muted-foreground">{s.label}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Features */}
        <section id="features" className="px-4 py-24 lg:py-32">
          <div className="mx-auto max-w-7xl lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
                Everything you need to trade binary options
              </h2>
              <p className="mt-4 text-lg text-muted-foreground">
                From signal generation to risk management, BinaryPulse keeps you ahead of the market.
              </p>
            </div>

            <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((f, i) => (
                <div
                  key={i}
                  className="group rounded-2xl glass-panel p-6 transition-all hover:-translate-y-1 hover:border-primary/40"
                >
                  <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-violet-gradient text-white shadow-lg shadow-primary/20 transition-transform group-hover:scale-110">
                    <f.icon className="h-6 w-6" />
                  </div>
                  <h3 className="font-display text-xl font-semibold text-foreground">{f.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="px-4 py-24 lg:py-32">
          <div className="mx-auto max-w-5xl overflow-hidden rounded-3xl bg-violet-gradient p-8 text-center shadow-2xl shadow-primary/25 sm:p-12 lg:p-16">
            <h2 className="font-display text-3xl font-bold text-primary-foreground sm:text-4xl">
              Ready to upgrade your trading?
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">
              Join 3,200+ traders using BinaryPulse to identify high-probability setups and trade with discipline.
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-4">
              <a
                href="/auth"
                className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-base font-semibold text-primary shadow-lg transition-all hover:bg-white/90 hover:scale-[1.02]"
              >
                Create free account
                <ArrowRight className="h-5 w-5" />
              </a>
              <a
                href="#pricing"
                className="inline-flex items-center gap-2 rounded-xl border border-white/30 bg-white/10 px-6 py-3.5 text-base font-semibold text-white backdrop-blur-sm transition-all hover:bg-white/20"
              >
                See plans
              </a>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/30 bg-surface/40 px-4 py-12 backdrop-blur-sm">
        <div className="mx-auto max-w-7xl lg:px-8">
          <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <div className="flex items-center gap-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-gradient text-white">
                  <CandlestickChart className="h-5 w-5" />
                </div>
                <span className="font-display text-xl font-bold text-foreground">
                  Binary<span className="text-primary">Pulse</span>
                </span>
              </div>
              <p className="mt-4 text-sm text-muted-foreground">
                Real-time forex analysis and binary options signals for traders who demand precision.
              </p>
            </div>

            <div>
              <h4 className="font-display text-sm font-semibold text-foreground">Product</h4>
              <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
                <li><a href="#features" className="hover:text-foreground">Features</a></li>
                <li><a href="#signals" className="hover:text-foreground">Signals</a></li>
                <li><a href="#pricing" className="hover:text-foreground">Pricing</a></li>
                <li><a href="#" className="hover:text-foreground">Changelog</a></li>
              </ul>
            </div>

            <div>
              <h4 className="font-display text-sm font-semibold text-foreground">Resources</h4>
              <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-foreground">Documentation</a></li>
                <li><a href="#" className="hover:text-foreground">API</a></li>
                <li><a href="#" className="hover:text-foreground">Community</a></li>
                <li><a href="#" className="hover:text-foreground">Blog</a></li>
              </ul>
            </div>

            <div>
              <h4 className="font-display text-sm font-semibold text-foreground">Legal</h4>
              <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-foreground">Privacy</a></li>
                <li><a href="#" className="hover:text-foreground">Terms</a></li>
                <li><a href="#" className="hover:text-foreground">Risk disclosure</a></li>
              </ul>
            </div>
          </div>

          <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-border/30 pt-8 sm:flex-row">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} BinaryPulse. All rights reserved.
            </p>
            <p className="text-xs text-muted-foreground">
              Trading involves risk. Past performance does not guarantee future results.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
