/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutMirrorRouteImport } from './routes/_layout/mirror'
import { Route as LayoutTradingRouteImport } from './routes/_layout/trading'
import { Route as ApiCronIngestCandlesRouteImport } from './routes/api/cron/ingest-candles'
import { Route as ApiPublicIqoptionWsRouteImport } from './routes/api/public/iqoption-ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMirrorRoute = LayoutMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTradingRoute = LayoutTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiCronIngestCandlesRoute = ApiCronIngestCandlesRouteImport.update({
  id: '/api/cron/ingest-candles',
  path: '/api/cron/ingest-candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIqoptionWsRoute = ApiPublicIqoptionWsRouteImport.update({
  id: '/api/public/iqoption-ws',
  path: '/api/public/iqoption-ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mirror': typeof LayoutMirrorRoute
  '/trading': typeof LayoutTradingRoute
  '/api/cron/ingest-candles': typeof ApiCronIngestCandlesRoute
  '/api/public/iqoption-ws': typeof ApiPublicIqoptionWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mirror': typeof LayoutMirrorRoute
  '/trading': typeof LayoutTradingRoute
  '/api/cron/ingest-candles': typeof ApiCronIngestCandlesRoute
  '/api/public/iqoption-ws': typeof ApiPublicIqoptionWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/mirror': typeof LayoutMirrorRoute
  '/_layout/trading': typeof LayoutTradingRoute
  '/api/cron/ingest-candles': typeof ApiCronIngestCandlesRoute
  '/api/public/iqoption-ws': typeof ApiPublicIqoptionWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mirror'
    | '/trading'
    | '/api/cron/ingest-candles'
    | '/api/public/iqoption-ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mirror'
    | '/trading'
    | '/api/cron/ingest-candles'
    | '/api/public/iqoption-ws'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/_layout/mirror'
    | '/_layout/trading'
    | '/api/cron/ingest-candles'
    | '/api/public/iqoption-ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCronIngestCandlesRoute: typeof ApiCronIngestCandlesRoute
  ApiPublicIqoptionWsRoute: typeof ApiPublicIqoptionWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/mirror': {
      id: '/_layout/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof LayoutMirrorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/trading': {
      id: '/_layout/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof LayoutTradingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/cron/ingest-candles': {
      id: '/api/cron/ingest-candles'
      path: '/api/cron/ingest-candles'
      fullPath: '/api/cron/ingest-candles'
      preLoaderRoute: typeof ApiCronIngestCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iqoption-ws': {
      id: '/api/public/iqoption-ws'
      path: '/api/public/iqoption-ws'
      fullPath: '/api/public/iqoption-ws'
      preLoaderRoute: typeof ApiPublicIqoptionWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutMirrorRoute: typeof LayoutMirrorRoute
  LayoutTradingRoute: typeof LayoutTradingRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMirrorRoute: LayoutMirrorRoute,
  LayoutTradingRoute: LayoutTradingRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCronIngestCandlesRoute: ApiCronIngestCandlesRoute,
  ApiPublicIqoptionWsRoute: ApiPublicIqoptionWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
